{"Timestamp":"5/11/2017 4:56:13 PM","Message":"Exception has been thrown by the target of an invocation.","InnerEx":"Test error","Source":"mscorlib","StackTrace":"   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)\r\n   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)\r\n   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\r\n   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)\r\n   at After.Socket_Handler.OnMessage(String message) in C:\\Users\\Typic\\Source\\Repos\\After\\After\\App_Code\\Socket_Handler.cs:line 60"}
{"Timestamp":"5/11/2017 4:56:13 PM","Message":"Test error","InnerEx":null,"Source":"App_Code.evpkou_b","StackTrace":"   at After.Message_Handlers.Queries.HandleFirstLoad(Object JsonMessage, Socket_Handler SH) in C:\\Users\\Typic\\Source\\Repos\\After\\After\\App_Code\\Message_Handlers\\Queries.cs:line 77"}
